### ISSUE TITLE
Building for IOS problems

### ISSUE THREAD

**Issue by tegaologe** [flxzt/ink-stroke-modeler-rs#3]
Building for IOS problem any idea would greatly appriaciated.

tega@MacBook-Pro rust % cargo build
   Compiling ink-stroke-modeler-rs v0.1.0 (/Users/tega/Desktop/Project/ink-stroke-modeler-rs)
   Compiling rust v0.1.0 (/Users/tega/Desktop/Project/writer/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 05s
tega@MacBook-Pro rust % cargo lipo
[INFO  cargo_lipo::meta] Will build universal library for ["rust"]
[INFO  cargo_lipo::lipo] Building "rust" for "aarch64-apple-ios"
   Compiling libc v0.2.151
   Compiling proc-macro2 v1.0.70
   Compiling unicode-ident v1.0.12
   Compiling autocfg v1.1.0
   Compiling memchr v2.6.4
   Compiling rustix v0.38.28
   Compiling version_check v0.9.4
   Compiling bitflags v2.4.1
   Compiling either v1.9.0
   Compiling thiserror v1.0.50
   Compiling syn v1.0.109
   Compiling serde v1.0.193
   Compiling serde_json v1.0.108
   Compiling log v0.4.20
   Compiling glob v0.3.1
   Compiling itertools v0.10.5
   Compiling unicode-width v0.1.11
   Compiling aho-corasick v1.1.2
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling regex-syntax v0.8.2
   Compiling indexmap v1.9.3
   Compiling prettyplease v0.2.15
   Compiling hashbrown v0.12.3
   Compiling once_cell v1.19.0
   Compiling ryu v1.0.16
   Compiling itoa v1.0.10
   Compiling clang-sys v1.6.1
   Compiling object v0.32.1
   Compiling rustversion v1.0.14
   Compiling cxxbridge-flags v1.0.110
   Compiling minimal-lexical v0.2.1
   Compiling termcolor v1.4.0
   Compiling quote v1.0.33
   Compiling nom v7.1.3
   Compiling itertools v0.9.0
   Compiling libloading v0.7.4
   Compiling syn v2.0.41
   Compiling home v0.5.5
   Compiling is_ci v1.1.1
   Compiling cc v1.0.83
   Compiling errno v0.3.8
   Compiling autocxx-bindgen v0.65.1
   Compiling unicode-linebreak v0.1.5
   Compiling smawk v0.3.2
   Compiling terminal_size v0.1.17
   Compiling textwrap v0.15.2
   Compiling codespan-reporting v0.11.1
   Compiling regex-automata v0.4.3
   Compiling is-terminal v0.4.9
   Compiling supports-unicode v2.0.0
   Compiling supports-color v2.1.0
   Compiling supports-hyperlinks v2.1.0
   Compiling backtrace v0.3.69
   Compiling link-cplusplus v1.0.9
   Compiling cxx v1.0.110
   Compiling which v4.4.2
   Compiling cexpr v0.6.0
   Compiling heck v0.4.1
   Compiling peeking_take_while v0.1.2
   Compiling fastrand v2.0.1
   Compiling lazycell v1.3.0
   Compiling rustc-hash v1.1.0
   Compiling bitflags v1.3.2
   Compiling owo-colors v3.5.0
   Compiling shlex v1.2.0
   Compiling tempfile v3.8.1
   Compiling atty v0.2.14
   Compiling num-traits v0.2.17
   Compiling humantime v2.1.0
   Compiling backtrace-ext v0.2.1
   Compiling indoc v1.0.9
   Compiling cfg-if v1.0.0
   Compiling lock_api v0.4.11
   Compiling gimli v0.28.1
   Compiling cxx-gen v0.7.110
   Compiling core-foundation-sys v0.8.6
   Compiling anyhow v1.0.75
   Compiling regex v1.10.2
   Compiling parking_lot_core v0.9.9
   Compiling env_logger v0.9.3
   Compiling adler v1.0.2
   Compiling miniz_oxide v0.7.1
   Compiling aquamarine v0.1.12
   Compiling strum_macros v0.24.3
   Compiling iana-time-zone v0.1.58
   Compiling dart-sys v4.0.2
   Compiling cmake v0.1.50
   Compiling autocxx v0.26.0
   Compiling path-slash v0.2.1
   Compiling scopeguard v1.2.0
   Compiling build-target v0.4.0
   Compiling addr2line v0.21.0
   Compiling smallvec v1.11.2
   Compiling rustc-demangle v0.1.23
   Compiling flutter_rust_bridge v1.82.5
   Compiling chrono v0.4.31
   Compiling num_cpus v1.16.0
   Compiling atomic v0.5.3
   Compiling threadpool v1.8.1
   Compiling parking_lot v0.12.1
   Compiling flutter_rust_bridge_macros v1.82.5
   Compiling lazy_static v1.4.0
   Compiling bytemuck v1.14.0
   Compiling serde_derive v1.0.193
   Compiling thiserror-impl v1.0.50
   Compiling miette-derive v5.10.0
   Compiling cxxbridge-macro v1.0.110
   Compiling allo-isolate v0.1.20
   Compiling miette v5.10.0
   Compiling moveit v0.6.0
   Compiling autocxx-parser v0.26.0
   Compiling autocxx-engine v0.26.0
   Compiling autocxx-macro v0.26.0
   Compiling autocxx-build v0.26.0
   Compiling ink-stroke-modeler-rs v0.1.0 (/Users/tega/Desktop/Project/ink-stroke-modeler-rs)
error: failed to run custom build command for `ink-stroke-modeler-rs v0.1.0 (/Users/tega/Desktop/Project/ink-stroke-modeler-rs)`

Caused by:
  process didn't exit successfully: `/Users/tega/Desktop/Project/writer/rust/target/debug/build/ink-stroke-modeler-rs-9c662ad39022bcea/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-ios = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_ios = None
  TARGET_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-ios = None
  CMAKE_GENERATOR_aarch64_apple_ios = None
  TARGET_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  running: "xcrun" "--show-sdk-path" "--sdk" "iphoneos"
  exit status: 0
  running: "xcrun" "--show-sdk-path" "--sdk" "iphoneos"
  exit status: 0
  CMAKE_PREFIX_PATH_aarch64-apple-ios = None
  CMAKE_PREFIX_PATH_aarch64_apple_ios = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-ios = None
  CMAKE_aarch64_apple_ios = None
  TARGET_CMAKE = None
  CMAKE = None
  running: cd "/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/Users/tega/Desktop/Project/ink-stroke-modeler-rs/abseil-cpp" "-DCMAKE_CXX_STANDARD=20" "-DCMAKE_POSITION_INDEPENDENT_CODE=ON" "-DCMAKE_PREFIX_PATH=/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out" "-DCMAKE_INSTALL_PREFIX=/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out" "-DCMAKE_INSTALL_LIBDIR=/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out/lib" "-DCMAKE_INSTALL_INCLUDEDIR=/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out/include" "-DBUILD_TESTING=OFF" "-DBUILD_SHARED_LIBS=OFF" "-DABSL_PROPAGATE_CXX_STD=ON" "-DCMAKE_SYSTEM_NAME=iOS" "-DCMAKE_SYSTEM_PROCESSOR=arm64" "-DCMAKE_C_FLAGS= -fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -fembed-bitcode" "-DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang" "-DCMAKE_CXX_FLAGS= -DABSL_FORCE_WAITER_MODE=4 -fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -fembed-bitcode" "-DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++" "-DCMAKE_ASM_FLAGS= -fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -fembed-bitcode" "-DCMAKE_ASM_COMPILER=/opt/homebrew/opt/llvm/bin/clang" "-DCMAKE_BUILD_TYPE=Release"
  -- The CXX compiler identification is Clang 17.0.6
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /opt/homebrew/opt/llvm/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17
  -- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17 - Failed
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - not found
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - no
  -- Configuring incomplete, errors occurred!

  --- stderr
  CMake Error at /opt/homebrew/Cellar/cmake/3.28.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Threads (missing: Threads_FOUND)
  Call Stack (most recent call first):
    /opt/homebrew/Cellar/cmake/3.28.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
    /opt/homebrew/Cellar/cmake/3.28.0/share/cmake/Modules/FindThreads.cmake:226 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:122 (find_package)

  thread 'main' panicked at /Users/tega/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR cargo_lipo] Failed to build "rust" for "aarch64-apple-ios": Executing env -i CARGO="/Users/tega/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo" CARGO_HOME="/Users/tega/.cargo" COLORTERM="truecolor" COMMAND_MODE="unix2003" DYLD_FALLBACK_LIBRARY_PATH="/Users/tega/.rustup/toolchains/stable-aarch64-apple-darwin/lib:/Users/tega/lib:/usr/local/lib:/usr/lib" GIT_ASKPASS="/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh" HOME="/Users/tega" HOMEBREW_CELLAR="/opt/homebrew/Cellar" HOMEBREW_PREFIX="/opt/homebrew" HOMEBREW_REPOSITORY="/opt/homebrew" INFOPATH="/opt/homebrew/share/info:/opt/homebrew/share/info:" LANG="en_US.UTF-8" LOGNAME="tega" MANPATH="/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/opt/homebrew/share/man::" MallocNanoZone="0" OLDPWD="/Users/tega/Desktop/Project/writer/rust" ORIGINAL_XDG_CURRENT_DESKTOP="undefined" PATH="/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/llvm/bin:/Users/tega/Documents/flutter/flutter/bin/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/Users/tega/Documents/flutter/flutter/bin/:/opt/homebrew/opt/llvm/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/tega/.cargo/bin:/Users/tega/Documents/flutter/flutter/bin:/Users/tega/.pub-cache/bin:/Users/tega/Documents/flutter/flutter/bin:/Users/tega/.pub-cache/bin" PWD="/Users/tega/Desktop/Project/writer/rust" RUSTUP_HOME="/Users/tega/.rustup" RUSTUP_TOOLCHAIN="stable-aarch64-apple-darwin" RUST_RECURSION_COUNT="1" SHELL="/bin/zsh" SHLVL="1" SSH_AUTH_SOCK="/private/tmp/com.apple.launchd.5R6GRcPpdt/Listeners" TERM="xterm-256color" TERM_PROGRAM="vscode" TERM_PROGRAM_VERSION="1.85.1" TMPDIR="/var/folders/x9/6dm6tdrd3d51dfq60ygnr4l80000gn/T/" USER="tega" USER_ZDOTDIR="/Users/tega" VSCODE_GIT_ASKPASS_EXTRA_ARGS="--ms-enable-electron-run-as-node" VSCODE_GIT_ASKPASS_MAIN="/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js" VSCODE_GIT_ASKPASS_NODE="/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)" VSCODE_GIT_IPC_HANDLE="/var/folders/x9/6dm6tdrd3d51dfq60ygnr4l80000gn/T/vscode-git-238848a368.sock" VSCODE_INJECTION="1" XPC_FLAGS="0x0" XPC_SERVICE_NAME="0" ZDOTDIR="/Users/tega" _="/Users/tega/.cargo/bin/cargo" __CFBundleIdentifier="com.microsoft.VSCode" __CF_USER_TEXT_ENCODING="0x1F5:0x0:0x52" "/Users/tega/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo" "--color" "auto" "build" "-p" "rust" "--target" "aarch64-apple-ios" "--lib" finished with error status: exit status: 101
tega@MacBook-Pro rust %

**Comment by tegaologe** [comment]
cargo_lipo::meta] Will build universal library for ["rust"]
[INFO  cargo_lipo::lipo] Building "rust" for "aarch64-apple-ios"
   Compiling ink-stroke-modeler-rs v0.1.0 (/Users/tega/Desktop/Project/ink-stroke-modeler-rs)
error: failed to run custom build command for `ink-stroke-modeler-rs v0.1.0 (/Users/tega/Desktop/Project/ink-stroke-modeler-rs)`

Caused by:
  process didn't exit successfully: `/Users/tega/Desktop/Project/writer/rust/target/debug/build/ink-stroke-modeler-rs-9c662ad39022bcea/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-ios = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_ios = None
  TARGET_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-ios = None
  CMAKE_GENERATOR_aarch64_apple_ios = None
  TARGET_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  running: "xcrun" "--show-sdk-path" "--sdk" "iphoneos"
  exit status: 0
  running: "xcrun" "--show-sdk-path" "--sdk" "iphoneos"
  exit status: 0
  CMAKE_PREFIX_PATH_aarch64-apple-ios = None
  CMAKE_PREFIX_PATH_aarch64_apple_ios = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-ios = None
  CMAKE_aarch64_apple_ios = None
  TARGET_CMAKE = None
  CMAKE = None
  running: cd "/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/Users/tega/Desktop/Project/ink-stroke-modeler-rs/abseil-cpp" "-DCMAKE_CXX_STANDARD=20" "-DCMAKE_POSITION_INDEPENDENT_CODE=ON" "-DCMAKE_PREFIX_PATH=/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out" "-DCMAKE_INSTALL_PREFIX=/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out" "-DCMAKE_INSTALL_LIBDIR=/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out/lib" "-DCMAKE_INSTALL_INCLUDEDIR=/Users/tega/Desktop/Project/writer/rust/target/aarch64-apple-ios/debug/build/ink-stroke-modeler-rs-613171f775d9216c/out/include" "-DBUILD_TESTING=OFF" "-DBUILD_SHARED_LIBS=OFF" "-DABSL_PROPAGATE_CXX_STD=ON" "-DCMAKE_SYSTEM_NAME=iOS" "-DCMAKE_SYSTEM_PROCESSOR=arm64" "-DCMAKE_C_FLAGS= -fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -fembed-bitcode" "-DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang" "-DCMAKE_CXX_FLAGS= -DABSL_FORCE_WAITER_MODE=4 -fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -fembed-bitcode" "-DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++" "-DCMAKE_ASM_FLAGS= -fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -fembed-bitcode" "-DCMAKE_ASM_COMPILER=/opt/homebrew/opt/llvm/bin/clang" "-DCMAKE_BUILD_TYPE=Release"
  -- Configuring incomplete, errors occurred!

  --- stderr
  CMake Error at /opt/homebrew/Cellar/cmake/3.28.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Threads (missing: Threads_FOUND)
  Call Stack (most recent call first):
    /opt/homebrew/Cellar/cmake/3.28.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
    /opt/homebrew/Cellar/cmake/3.28.0/share/cmake/Modules/FindThreads.cmake:226 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:122 (find_package)


  thread 'main' panicked at /Users/tega/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
     1: core::panicking::panic_fmt
               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
     2: cmake::fail
               at /Users/tega/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5
     3: cmake::run
               at /Users/tega/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1076:9
     4: cmake::Config::build
               at /Users/tega/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:813:13
     5: build_script_build::main
               at ./build.rs:18:35
     6: core::ops::function::FnOnce::call_once

**Comment by tegaologe** [comment]
-- The CXX compiler identification is Clang 17.0.6
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /opt/homebrew/opt/llvm/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17
  -- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17 - Failed
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - not found
  -- Check if compiler accepts -pthread
  -- Check if compiler accepts -pthread - no
  -- Configuring incomplete, errors occurred!
  
  
  


 CMAKE_TOOLCHAIN_FILE_aarch64-apple-ios = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_ios = None
  TARGET_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-ios = None
  CMAKE_GENERATOR_aarch64_apple_ios = None
  TARGET_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  running: "xcrun" "--show-sdk-path" "--sdk" "iphoneos"
  exit status: 0
  running: "xcrun" "--show-sdk-path" "--sdk" "iphoneos"
  exit status: 0
  CMAKE_PREFIX_PATH_aarch64-apple-ios = None
  CMAKE_PREFIX_PATH_aarch64_apple_ios = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-ios = None
  CMAKE_aarch64_apple_ios = None
  TARGET_CMAKE = None
  CMAKE = None

**Comment by flxzt** [comment]
@tegaologe with the rust rewrite that happened in #4 you shouldn't have any problems building anymore, since there are only pure-rust dependencies now
